[program:GUI]
directory = /home/pi/Documents/Ruca
command = gunicorn Ruca2_GUI:app -k gevent -t 150 -w 4 -b 0.0.0.0:8000
user = pi
autostart = yes
autorestart = true
stopasgroup = true
stderr_logfile = /var/log/Ruca2_GUI.err.log
stdout_logfile = /var/log/Ruca2_GUI.out.log

[program:rueda]
directory = /home/pi/Documents/Ruca
command = python3 Ruca2_rueda.py
user = pi
autostart = yes
autorestart = no
stopasgroup = true
stderr_logfile = /var/log/Ruca2_rueda.err.log
stdout_logfile = /var/log/Ruca2_rueda.out.log

[program:platina]
directory = /home/pi/Documents/Ruca
command = python3 Ruca2_platina.py
user = pi
autostart = no
autorestart = no
stopasgroup = true
stderr_logfile = /var/log/Ruca2_platina.err.log
stdout_logfile = /var/log/Ruca2_platina.out.log
