[program:GUI]
directory = /home/pi/Documents/Ruca
command = gunicorn Ruca2_GUI:app -k gevent -t 150 -w 4 -b 0.0.0.0:8000
user = pi
autostart = yes
autorestart = true
stopasgroup = true
stderr_logfile = /dev/null
stdout_logfile = /dev/null

[program:rueda]
directory = /home/pi/Documents/Ruca
command = python3 Ruca2_rueda.py
user = pi
autostart = yes
autorestart = no
stopasgroup = true
stderr_logfile = /dev/null
stdout_logfile = /dev/null

[program:platina]
directory = /home/pi/Documents/Ruca
command = python3 Ruca2_platina.py
user = pi
autostart = no
autorestart = no
stopasgroup = true
stderr_logfile = /dev/null
stdout_logfile = /dev/null

[program:mqtt_control]
directory = /home/pi/Documents/Ruca
command = python3 Ruca2_mqtt.py
user = pi
autostart = yes
autorestart = true
stopasgroup = true
stderr_logfile = /dev/null
stdout_logfile = /dev/null

[program:mqtt_status]
directory = /home/pi/Documents/Ruca
command = python3 Ruca2_mqtt_status.py
user = pi
autostart = yes
autorestart = true
stopasgroup = true
stderr_logfile = /dev/null
stdout_logfile = /dev/null

[program:reinicio_automatico]
directory=/home/pi/Documents/Ruca
command=python3 reinicio_ruca.py
user = pi
autostart = yes
autorestart = true
stopasgroup = true
stderr_logfile = /dev/null
stdout_logfile = /dev/null